### ISSUE TITLE
Unraid 6.12 compatibility

### ISSUE THREAD

**Issue by ashishpandey** [CyanLabs/corsairpsu-unraid#3]
Needs changes to be compatible with unraid 6.12+, currently marked incompatible on RC1
https://forums.unraid.net/topic/86715-corsair-rmi-hxi-axi-psu-statistics-cyanlabss-fork/?do=findComment&comment=1241308

**Comment by giganode** [comment]
> Needs changes to be compatible with unraid 6.12+, currently marked incompatible on RC1 https://forums.unraid.net/topic/86715-corsair-rmi-hxi-axi-psu-statistics-cyanlabss-fork/?do=findComment&comment=1241308

I have a working version running right now. I am just waiting for permission to continue this plugin, because the original maintainer doesn't use unraid anymore.

**Comment by fma965** [comment]
Repo Archived, Please use https://github.com/giganode/corsairpsu-unraid
